[package]
name = "cubicle"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
cap-std = "0.25.2"
clap = { version = "3.2.16", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
shlex = "1.1.0"
