[package]
name = "cubicle"
version = "0.0.0"

categories = ["command-line-utilities", "virtualization"]
description = "Manage isolated development environments"
keywords = ["cli", "container", "dev-environment", "docker", "sandbox"]
license = "MIT"
repository = "https://github.com/ongardie/cubicle"

default-run = "cub"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cub"
path = "src/main.rs"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
cap-std = "3.0.0"
clap = { version = "4.4.18", features = ["derive", "wrap_help"] }
clap_complete = "4.4.9"
indoc = "2.0.4"
# this is a dev-dependency but needed in `system_test` bin
insta = "1.34.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking"] }
rustix = { version = "0.38.30", features = ["fs", "process"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
sha2 = "0.10.8"
shlex = "1.3.0"
tar = "0.4.40"
tempfile = "3.9.0"
toml = "0.8.9"
wildmatch = "2.3.0"

[dev-dependencies]

# See https://docs.rs/insta/latest/insta/#optional-faster-runs
[profile.dev.package.insta]
opt-level = 3

# See https://docs.rs/insta/latest/insta/#optional-faster-runs
[profile.dev.package.similar]
opt-level = 3
